### ISSUE TITLE
Variable wird nicht benötigt

### ISSUE THREAD

**Issue by gossie** [sengsei/nf_freitag_passwortvalidierung#1]
Die `currentState`-Variable wird nicht benötigt, da der Wert nirgends verändert wird. Am Ende der Methode kann also einfach `true` zurückgegeben werden.

https://github.com/sengsei/nf_freitag_passwortvalidierung/blob/23690b41f5701442e13af25ecabdae1b6638bfe5/src/main/java/PasswordValidation.java#L6

**Comment by sengsei** [comment]
issue fixed
