### ISSUE TITLE
Prüfungen werden doppelt durchgeführt

### ISSUE THREAD

**Issue by gossie** [sengsei/nf_freitag_passwortvalidierung#2]
Hier wird jede Prüfung doppelt durchgeführt um die Logausgaben ausgeben zu können. Stattdessen würde die Ausgaben in den entsprechenden Methoden machen.

https://github.com/sengsei/nf_freitag_passwortvalidierung/blob/23690b41f5701442e13af25ecabdae1b6638bfe5/src/main/java/PasswordValidation.java#L16

**Comment by sengsei** [comment]
output outsourced to methods
