### ISSUE TITLE
Public API vs interne Implementierung

### ISSUE THREAD

**Issue by gossie** [sengsei/nf_freitag_passwortvalidierung#3]
Alles Methoden außer `validatePassword` und `validatePasswordArray` würde ich `private` machen. Wenn du die Methoden im richtigen Projekt später `public` machst, werden sie benutzt werden und du kannst deine interne Implementierung nicht einfach so ändern.

**Comment by sengsei** [comment]
Meine Frage ist, wie kann ich die bisherigen Tests retten. Wenn ich die Hilfsmethoden auf private setze habe ich ja kein Zugriff mehr in den Tests.

**Comment by gossie** [comment]
So wie die Tests jetzt sind, werden sie dann nicht bleiben können. Es wird dann nur noch einen Test mit `assertTrue` geben, nämlich den, wo ein Passwort getestet wird, das allen Anforderungen entspricht.
Bei allen anderen Tests müsste ein Passwort übergeben werden bei dem n-1 Anforderungen erfüllt sind.

**Comment by sengsei** [comment]
danke das hilft auf jeden Fall weiter

**Comment by sengsei** [comment]
problem fixed
